Controllers films users
Alechkasp/java-filmorate pull request #1
Opened 2022-10-30 10:53 UTC by Alechkasp

2022-10-30 14:11 UTC, AnastasiyaFomkina requested changes
Можешь, пожалуйста, также добавить в файл `.gitignore` игнорирование всех `.DS_Store` бинарников (нужно просто добавить строку .DS_Store) и удалить эти файлы из реквеста

2022-10-30 14:11 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +import org.springframework.web.bind.annotation.*;
_Саморазвитие_
В коммерческой разработке не принято использовать `wildcard` в импортах.
Вот отличная [статья](https://struchkov.dev/blog/using-wildcard-imports-in-java/) почему и как настроить идею, чтобы избавиться от `*`
Кстати, в IDEA есть отличное сочетание клавиш `Ctrl + Alt + O` - при нажатии сочетания в нужном классе автоматически оптимизируются импорты и удаляются ненужные

2022-10-30 14:11 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        log.debug("Получен запрос GET /films.");
Логирование - это очень удобно, молодец 👍

2022-10-30 14:11 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public InMemoryHistoryFilmService filmService = new InMemoryHistoryFilmService();
- лучше определять интерфейс (`FilmService`), а создавать объект с конкретной реализацией. 
- в коммерческой разработке принято максимально скрывать все поля класса, если есть такая возможность, чтобы нечаянно не изменить состояние объекта из какого-то другого места в коде. В данном случае `FilmService` используется только внутри `FilmController`, поэтому лучше заменить модификатор доступа на самый строгий

2022-10-30 14:11 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        filmService.addFilm(film);
Лучше использовать возвращаемое значение метода `addFilm`, так как в будущем может случится, что `film`, который мы получили в параметрах, будет отличаться от того, который мы добавили в хранилище

```suggestion
        Film addedFilm = filmService.addFilm(film);
```

2022-10-30 14:11 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        filmService.updateFilm(film);
Здесь тоже лучше использовать возвращаемое значение метода

2022-10-30 14:11 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    private final InMemoryHistoryUserService userService = new InMemoryHistoryUserService();
Лучше определить интерфейс

2022-10-30 14:11 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        userService.updateUser(user);
В методах `create` и `update` нужно использовать возвращаемое значение,  как и в `FilmController`

2022-10-30 14:11 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/exception/ValidationException.java
> +public class ValidationException extends RuntimeException {
👍

2022-10-30 14:11 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/services/InMemoryHistoryFilmService.java
> +    public static final LocalDate DATE_FIRST_RELEASE = LocalDate.of(1895, 12, 28);
`DATE_FIRST_RELEASE` используется только внутри данного класса, лучше изменить модификатор доступа на _private_

2022-10-30 14:11 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/services/InMemoryHistoryFilmService.java
> +    int id = 0;
А здесь нужно добавить модификатор доступа

2022-10-30 14:11 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/services/InMemoryHistoryFilmService.java
> +    private final HashMap<Integer, Film> films = new HashMap<>();
Лучше определять интерфейс, а создавать объект с конкретной реализацией, так программа станет более гибкой и не будет завязана на определенные структуры данных

2022-10-30 14:11 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/services/InMemoryHistoryUserService.java
> +    private final HashMap<Integer, User> users = new HashMap<>();
Здесь тоже лучше определить интерфейс

2022-10-30 14:11 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/services/InMemoryHistoryUserService.java
> +    int id = 0;
Нужно добавить модификатор доступа

2022-10-30 14:11 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/services/InMemoryHistoryUserService.java
> +        if ((user.getName() == null) || (user.getName().equals(""))) {
_Саморазвитие_
```suggestion
        if ((user.getName() == null) || (user.getName().isBlank())) {
```
`.isBlank()` - метод строки, который проверят, что строка не пустая
Вот [здесь](https://www.baeldung.com/java-blank-empty-strings) чуть больше проверки строк

2022-10-30 14:11 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/FilmTest.java
> +public class FilmTest {
Молодец, что добавила тесты 👍

2022-10-30 21:05 UTC, Alechkasp commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +import org.springframework.web.bind.annotation.*;
поправила

2022-10-30 21:05 UTC, Alechkasp commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        log.debug("Получен запрос GET /films.");
спасибо 👍

2022-10-30 21:05 UTC, Alechkasp commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public InMemoryHistoryFilmService filmService = new InMemoryHistoryFilmService();
поправила

2022-10-30 21:05 UTC, Alechkasp commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        filmService.addFilm(film);
поправила

2022-10-30 21:05 UTC, Alechkasp commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        filmService.updateFilm(film);
поправила

2022-10-30 21:06 UTC, Alechkasp commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    private final InMemoryHistoryUserService userService = new InMemoryHistoryUserService();
поправила

2022-10-30 21:06 UTC, Alechkasp commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        userService.updateUser(user);
поправила

2022-10-30 21:06 UTC, Alechkasp commented on src/main/java/ru/yandex/practicum/filmorate/services/InMemoryHistoryFilmService.java
> +    public static final LocalDate DATE_FIRST_RELEASE = LocalDate.of(1895, 12, 28);
поправила

2022-10-30 21:06 UTC, Alechkasp commented on src/main/java/ru/yandex/practicum/filmorate/services/InMemoryHistoryFilmService.java
> +    int id = 0;
добавила

2022-10-30 21:07 UTC, Alechkasp commented on src/main/java/ru/yandex/practicum/filmorate/services/InMemoryHistoryFilmService.java
> +    private final HashMap<Integer, Film> films = new HashMap<>();
поправила

2022-10-30 21:07 UTC, Alechkasp commented on src/main/java/ru/yandex/practicum/filmorate/services/InMemoryHistoryUserService.java
> +    private final HashMap<Integer, User> users = new HashMap<>();
поправила

2022-10-30 21:07 UTC, Alechkasp commented on src/main/java/ru/yandex/practicum/filmorate/services/InMemoryHistoryUserService.java
> +    int id = 0;
поправила

2022-10-30 21:07 UTC, Alechkasp commented on src/main/java/ru/yandex/practicum/filmorate/services/InMemoryHistoryUserService.java
> +        if ((user.getName() == null) || (user.getName().equals(""))) {
поправила

2022-10-31 06:50 UTC, AnastasiyaFomkina approved these changes

2022-11-01 12:38 UTC, merged