Add database
Alechkasp/java-filmorate pull request #3
Opened 2022-12-13 12:47 UTC by Alechkasp

2022-12-14 10:36 UTC, AnastasiyaFomkina requested changes

2022-12-14 10:36 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private void validateFilmReleaseDate(LocalDate date) {
Лучше перенести данный метод в сервис, так как он отвечает за бизнес-логику

2022-12-14 10:36 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +public interface FilmService {
👍

2022-12-14 10:36 UTC, afomkina commented on src/test/java/ru/yandex/practicum/filmorate/FilmDbStorageTest.java
> +public class FilmDbStorageTest {
Нужно добавить еще два тестовых класса для `MpaStorage` и `GenreStorage`

2022-12-14 10:36 UTC, afomkina commented on src/test/java/ru/yandex/practicum/filmorate/FilmTest.java
> -public class FilmTest {
Не нужно удалять тесты, лучше перенести их в корректный пакет, переименовать и немного доработать

2022-12-14 10:36 UTC, afomkina commented on src/test/java/ru/yandex/practicum/filmorate/UserTest.java
> -public class UserTest {
Верни, пожалуйста, тест

2022-12-14 10:36 UTC, afomkina commented on src/main/resources/application.properties
> +#spring.datasource.url=jdbc:h2:mem:filmorate
Лучше не комментировать, а удалять

2022-12-15 17:09 UTC, Alechkasp commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private void validateFilmReleaseDate(LocalDate date) {
Перенесла

2022-12-15 17:09 UTC, Alechkasp commented on src/test/java/ru/yandex/practicum/filmorate/FilmDbStorageTest.java
> +public class FilmDbStorageTest {
Добавила

2022-12-15 17:09 UTC, Alechkasp commented on src/test/java/ru/yandex/practicum/filmorate/FilmTest.java
> -public class FilmTest {
Вернула тесты

2022-12-15 17:09 UTC, Alechkasp commented on src/test/java/ru/yandex/practicum/filmorate/UserTest.java
> -public class UserTest {
Вернула тесты

2022-12-15 17:09 UTC, Alechkasp commented on src/main/resources/application.properties
> +#spring.datasource.url=jdbc:h2:mem:filmorate
Удалила

2022-12-16 08:19 UTC, AnastasiyaFomkina approved these changes

2022-12-16 09:42 UTC, merged